version: '3'
services:
  nginx:
    image: maximus905/nginx
    ports:
      - "8080:80"
    volumes:
      - "./www:/var/www"
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/conf.d:/etc/nginx/conf.d"
      - "./conf/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - phpsocket:/var/run
  php:
    image: maximus905/php-fpm
    environment:
      - LISTEN_SOCKET=yes
      - TZ=Europe/Moscow
    volumes:
      - ./www:/var/www
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/custom.d:/usr/local/etc/php/custom.d
      - phpsocket:/var/run
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - voice_db:/var/lib/postgresql/data
      - ./db_backups:/var/db_backups
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  phpsocket:
  voice_db:
    external: true