version: '3'
services:
  nginx:
    image: maximus905/nginx
    ports:
      - "8082:80"
    volumes:
      - ./www:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/sites-enabled:/etc/nginx/conf.d
      # - phpsocket:/var/run
    command: [nginx-debug, '-g', 'daemon off;']
  php:
    image: maximus905/php-fpm:7.2.10
    environment:
      - DEVELOPMENT_MODE=yes
      # - LISTEN_SOCKET=
      - TZ=Europe/Moscow
    working_dir: /var/www/netcmdb-loc.rs.ru
    volumes:
      - ./www:/var/www
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/custom.d:/usr/local/etc/php/custom.d
      # - phpsocket:/var/run
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - voice_db:/var/lib/postgresql/data
      - ./db_backups:/var/db_backups
  adminer:
    image: adminer
    ports:
      - 8081:8080
volumes:
  # phpsocket:
  voice_db:
    external: true